pipeline{
    agent any
    options{
        skipStagesAfterUnstable()
    }
    stages{
        stage('Checking Repository'){
            steps{
                checkout scm
            }
        }
        stage('Build Docker Image'){
            steps{
                script{
                    app = docker.build("yelb/nginx", "./yelb-ui")
                }
            }   
        }
        stage('Deploy') {
            steps {
                script{
                    docker.withRegistry('https://720766170633.dkr.ecr.us-east-2.amazonaws.com 749295092856.dkr.ecr.us-west-1.amazonaws.com/test_registry', 'AWS_ECR') {
                    app.push("latest")
                    }
                }
            }
    }
}