pipeline{
    agent any
    options{
        skipStagesAfterUnstable()
        skipDefaultCheckout(true)
    }
    stages{
        stage('Checking Credetentials and Repository Changes'){
            steps{
                sh 'rm -f ~/.dockercfg ~/.docker/config.json || true'
                checkout scm
            }
        }
        stage('Build Docker Image'){
            when{
                changeset "./yelb-ui/Dockerfile"
            }
            steps{
                script{
                    app = docker.build("yelb-ui-nginx:${env.BUILD_ID}", "./yelb-ui")
                }
            }   
        }
        stage('Testing Docker Image'){
            steps{
                sh '''
                    echo 'Testing Docker Image'
                    sleep 5
                    echo 'TEST SUCCESS'
                '''
            }
        }
        stage('Deploy') {
            when{
             changeset "./yelb-ui/Dockerfile"
            }
            steps {
                script{
                    docker.withRegistry('https://749295092856.dkr.ecr.us-west-1.amazonaws.com/yelb-ui-nginx', 'ecr:us-west-1:AWS_ECR') {
                        app.push()
                    }
                }
            }
        }
    }
}